redpanda:
  developer_mode: true
  data_directory: /var/lib/redpanda/data
  empty_seed_starts_cluster: true
  rpc_server:
    address: 127.0.0.1
    port: 33145
  kafka_api:
    - address: 127.0.0.1
      port: 9092
  advertised_kafka_api:
    - address: 127.0.0.1
      port: 9092
  admin:
    - address: 127.0.0.1
      port: 9644
  seed_servers: []
rpk:
  kafka_api:
    brokers:
      - 127.0.0.1:9092
  admin_api:
    addresses:
      - 127.0.0.1:9644
