[supervisord]
nodaemon=false
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:clickhouse]
command=/usr/bin/clickhouse-server --config-file=/etc/clickhouse-server/config.xml
user=clickhouse
autostart=true
autorestart=false
priority=10
stdout_logfile=/tmp/clickhouse.log
stderr_logfile=/tmp/clickhouse.err.log
