[supervisord]
nodaemon=false
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:postgres]
command=/usr/lib/postgresql/16/bin/postgres -D /var/lib/postgresql/data
user=postgres
autostart=true
autorestart=false
priority=10
stdout_logfile=/tmp/postgres.log
stderr_logfile=/tmp/postgres.err.log

[program:clickhouse]
command=/usr/bin/clickhouse-server --config-file=/etc/clickhouse-server/config.xml
autostart=true
autorestart=false
priority=20
stdout_logfile=/tmp/clickhouse.log
stderr_logfile=/tmp/clickhouse.err.log
